### ISSUE TITLE
SPSS file is unreadable when saved with new Float64 dtype and missing_range

### ISSUE THREAD

**Issue by eirki** [Roche/pyreadstat#150] opened 2021-11-02 10:03 UTC
Saving a dataframe using Pandas' new Float64 dtype (notice the capital F), and `missing_ranges` causes the resulting file to be unreadable - by pyreadstat or SPSS. I haven't been able to find much documentation about this dtype, but to my understanding it is related to the new nullable integer dtype (which seems to working fine in Pyreadstat).

To reproduce:

```python
pyreadstat.write_sav(
        df=pd.DataFrame({"a": pd.Series([1,2,3], dtype=pd.Float64Dtype())}),
        dst_path="myfile.sav",
        missing_ranges={"a": [{"hi": 1, "lo":1}]}
    )
pyreadstat.read_sav("myfile.sav")
```

```
---------------------------------------------------------------------------
ReadstatError                             Traceback (most recent call last)
<ipython-input-78-fa650d82e8c0> in <module>
      4         missing_ranges={"a": [{"hi": 1, "lo":1}]}
      5     )
----> 6 pyreadstat.read_sav("myfile.sav")

pyreadstat/pyreadstat.pyx in pyreadstat.pyreadstat.read_sav()
pyreadstat/_readstat_parser.pyx in pyreadstat._readstat_parser.run_conversion()
pyreadstat/_readstat_parser.pyx in pyreadstat._readstat_parser.run_readstat_parser()
pyreadstat/_readstat_parser.pyx in pyreadstat._readstat_parser.check_exit_status()
ReadstatError: Invalid file, or file has unsupported features
```

System:
- pandas==1.2.4
- pyreadstat==1.1.3

**Comment by ofajardo** [comment] 2021-11-09 11:36
thanks a lot for the very reproducible issue. The issue is solved on the dev branch and will be incorporated into master on the next release. 
This introduces the need for pandas to be at least in version 1.2.0 otherwise these new types would not be there causing an error.

**Comment by eirki** [comment] 2021-11-12 08:52
Thanks very much! Would you like me to close the issue?

**Comment by ofajardo** [comment] 2021-11-12 08:54
I'll close when I do the new release, thanks.

**Comment by ofajardo** [comment] 2021-12-02 15:40
version 1.1.4 is out with this change.

**Closed by ofajardo** 2021-12-02 15:40 UTC
Labels: enhancement
