### ISSUE TITLE
write_xpt version = 8 files not able to be read by SAS 

### ISSUE THREAD

**Issue by YCK2386620654** [Roche/pyreadstat#176] opened 2022-04-19 05:40 UTC
write_xpt version = 8 files not able to be read by SAS

**Comment by ofajardo** [comment] 2022-04-19 07:24
As indicated in the issue template please provide all the details requested there, and the code to reproduce the issue and the file to reproduce the issue. Please do not skip what is requested in the issue template. 

Right now I cannot reproduce the issue at all, files are open OK in SAS. Provide more details and how to reproduce the issue.

**Comment by YCK2386620654** [comment] 2022-04-19 09:08
I used some examples to create an XPT file and then open it through SAS to show not a SAS Version 6.0 file
![image](https://user-images.githubusercontent.com/61236892/163969940-926f2cb5-214f-4db2-8f1d-1bf2a08f60e2.png)

**Comment by YCK2386620654** [comment] 2022-04-19 09:22
Thank you, I X[XPT2LOC](https://documentation.sas.com/doc/en/pgmsascdc/v_006/movefile/p1tp8gighlgeifn173i6kzw2w3bu.htm). I know why

**Comment by YCK2386620654** [comment] 2022-04-19 09:23
Thank you, I X[XPT2LOC](https://documentation.sas.com/doc/en/pgmsascdc/v_006/movefile/p1tp8gighlgeifn173i6kzw2w3bu.htm). I know why

**Comment by YCK2386620654** [comment] 2022-04-19 09:23
Thank you, I X[XPT2LOC](https://documentation.sas.com/doc/en/pgmsascdc/v_006/movefile/p1tp8gighlgeifn173i6kzw2w3bu.htm). I know why

**Comment by ofajardo** [comment] 2022-04-19 10:11
I assume this is solved, therefore closing it.

**Closed by ofajardo** 2022-04-19 10:11 UTC
